eureka:
  client:
    serviceUrl:
      defaultZone: http://sw-eureka-peer1:8761/eureka, http://sw-eureka-peer2:8762/eureka

server:
  port: 8080

messages: Squat, 5x5, FBW, Deadlift, TUT, Bench Press, OHP